;Copyright 2017 Lexmark International, Inc. All rights reserved.
;Permission is granted for redistribution of this file as long as this copyright notice is intact and
;the content of the file is not altered in any way from its original form.
[DriverConfig]
DataFile=LMUX1L50.GPD
RequiredFiles=UNIRES.DLL,STDNAMES.GPD,STDDTYPE.GDL,STDSCHEM.GDL,STDSCHMX.GDL,XPSSVCS.DLL,MSXPSINC.GPD,P6DISP.GPD,PCL5ERES.DLL,LOCALE.GPD,MSxpsPCL6.dll,PJL.GPD,P6FONT.GPD,PCLXL.GPD
PrinterDriverID={E47CDEF8-C0FC-4711-B671-C251E322913A}
ConstraintScript=LMUX1LConst.js
DriverCategory=PrintFax.Printer
DevModeMap=LMUX1Ldmmap.xml
EventFile=LMUX1L5de.xml
QueueProperties=LMUX1Lqpb.xml
PropertyBag=LMUX1L50.dpb
ResourceFile=LMUX1LRD.DLL

[BidiFiles]
BidiSPMFile=LMUX1L5B.XML
BidiWSDFile=LMUX1L5BW.XML
BidiUSBFile=LMUX1L5BU.XML
BidiUSBJSFile=LMUX1LUSBJS.js

[DriverRender]
PageOutputQuality.Fax=MxdcImageType.JPEGHigh
PageOutputQuality.Draft=MxdcImageType.JPEGMedium
PageOutputQuality.High=MxdcImageType.PNG
PageOutputQuality.Normal=MxdcImageType.JPEGLow

[PrinterExtensions]
DriverEvent=PrinterExtension.exe,{E47CDEF8-C0FC-4711-B671-C251E322913A}
PrintPreferences=PrinterExtension.exe,{E47CDEF8-C0FC-4711-B671-C251E322913A}

